### ISSUE TITLE
create configshell-fb package broke pip2spack

### ISSUE THREAD

**Issue by Spedoske** [NexSabre/pip2spack#16]
Pip2spack generates a wrong uri when creating configshell-fb package

```
(wrong) url      = "https://pypi.io/packages/source/c/configshell/configshell-fb-1.1.29.tar.gz"
(right) url      = "https://pypi.io/packages/source/c/configshell-fb/configshell-fb-1.1.29.tar.gz"
```

This line may lead to the problem.
https://github.com/NexSabre/pip2spack/blob/f2506ab42605b3a199c7ca198a49d1ed4ded7585/src/pip2spack/core/pypi_package.py#L64

**Comment by NexSabre** [comment]
Thanks for reporting the issue, I introduce solution for it with PR #17
